web:
    image: davischang/wordpress:24-90887bbd5ab4505425d93fe66f8b4c36840a83de
#    volumes:
#      - ./wordpress_data/:/var/www/html
    links:
        - mysql
    environment:
        - WORDPRESS_DB_PASSWORD=password
    ports:
        - 80:80
mysql:
    image: mysql:5.7
#    volumes:
#        - ./mysql_data:/var/lib/mysql
    environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=wordpress

phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
        - mysql:mysql
    ports:
        - 28017:80
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: password
