# base image
docker build -t wordpress-base-img .


#!/bin/bash -xe
DOCKER_REGISTRY_USER=${DOCKER_REGISTRY_USER}
DOCKER_REGISTRY_PASSWORD=${DOCKER_REGISTRY_PASSWORD}
DOCKER_REGISTRY_EMAIL=${DOCKER_REGISTRY_EMAIL}

TAG="${BUILD_NUMBER}-${GIT_COMMIT}"
TIMESTAMP=`date +"%Y%m%d%H%M%S"`
DATE=$(date +%d-%m-%Y" "%H:%M:%S)

docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" -e "$DOCKER_REGISTRY_EMAIL"

# base image
docker build \
  -t "$DOCKER_REPO_NAME:$TAG" \
  .


docker tag -f "$DOCKER_REPO_NAME:$TAG" "$DOCKER_REGISTRY_HOST/$DOCKER_REPO_NAME:$TAG"
docker tag -f "$DOCKER_REPO_NAME:$TAG" "$DOCKER_REGISTRY_HOST/$DOCKER_REPO_NAME:latest"
docker push "$DOCKER_REGISTRY_HOST/$DOCKER_REPO_NAME:$TAG"
docker push "$DOCKER_REGISTRY_HOST/$DOCKER_REPO_NAME:latest"
