web:
    image: davischang/wordpress
    volumes:
      - ./wordpress/:/var/www/html
    links:
        - mysql
    environment:
        - WORDPRESS_DB_PASSWORD=password
    ports:
        - "8000:80"
mysql:
    image: mysql:5.7
    volumes:
        - ./mysqldata:/var/lib/mysql
    environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=wordpress

phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
        - mysql:mysql
    ports:
        - 8001:80
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: password
