version: '2'
services:
    web:
        image: ${DOCKER_WEB}
        volumes:
          - ./wordpress_data/:/var/www/html
        links:
            - mysql
        environment:
            - WORDPRESS_DB_PASSWORD=password
        ports:
            - ${WORPESS_PORT_80_TCP_PORT}:80
    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql_data:/var/lib/mysql
        environment:
             - MYSQL_ROOT_PASSWORD=password
             - MYSQL_DATABASE=wordpress

    phpmyadmin:
        image: corbinu/docker-phpmyadmin
        links:
            - mysql:mysql
        ports:
            - ${PHPMYADMIN_PORT_28017_TCP_PORT}:80
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: password
